### ISSUE TITLE
Adicionar definição do módulo antes de usar.

### ISSUE THREAD

**Issue by sadjow** [igorcosta/ng-filters-br#3]
No arquivo dist:
https://github.com/igorcosta/ng-filters-br/blob/master/dist/ng-filters-br.js#L11

Está usando o módulo, sem antes definir. Isso está dando problema na hora de usar.
Precisei adicionar direto no arquivo, no inicio: `angular.module('brasil.filters', [])'` para definir o módulo.

**Comment by igorcosta** [comment]
Opa, Obrigado irei corrigir na próxima versão.

**Comment by sadjow** [comment]
:+1:
