### ISSUE TITLE
Data em formato amigavél

### ISSUE THREAD

**Issue by diegograssato** [igorcosta/ng-filters-br#5]
Olá estou disposto a contribuir com seu projeto, poderíamos adicionar um filtro, que forneça a saída da ta em um formato amigável, exemplo:
Amanhã às 12:30
Ontem às 15:30
Hoje `as 18:00
.....etc....

Se você quiser me adicione como contribuidor que eu adiciono o filtro que faz essa manipulação.

**Comment by igorcosta** [comment]
ótimo, pode fazer um pull request, revisarei e incluirei no projeto.
