### ISSUE TITLE
Adicionar Filtro para Datas

### ISSUE THREAD

**Issue by ViniciusTavares** [igorcosta/ng-filters-br#6]
Os filtros estão maneiros amigo, mas seria uma boa adicionar filtros para data formato nacional também, com descrições tipo '20 de Nov de 2015'. Ficaria show! 

Abraços

**Comment by denislins** [comment]
Desenterrando a issue um pouco, você consegue fazer isso pelo angular mesmo, sem plugins. Basta colocar o arquivo de locale pt-br e usar o filtro padrão de data.
